services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deinbox-app
    mem_limit: 4g
    cpus: 4
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-bullmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_CACHE_URL}
      - REDIS_BULLMQ_URL=${REDIS_BULLMQ_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]  # change to "start" for production

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deinbox-worker
    mem_limit: 2g
    cpus: 2
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis-bullmq:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_CACHE_URL}
      - REDIS_BULLMQ_URL=${REDIS_BULLMQ_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "worker"]

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: always
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-bullmq:
    image: redis:7
    container_name: redis-bullmq
    restart: always
    command: >
      redis-server
      --appendonly yes
      --maxmemory-policy noeviction
    ports:
      - "6380:6379"
    volumes:
      - redis_bullmq_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_cache_data:
  redis_bullmq_data:
